name: CI-Build-linux-and-macos

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "39 7 * * 1"
    
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install gcovr
      run: pip install gcovr

    - name: Install Linux dependencies with caching
      uses: awalsh128/cache-apt-pkgs-action@latest
      if: runner.os == 'Linux'
      with:
          # put your list of apt packages here for the dependencies you need
          packages: libxi-dev libxmu-dev pkg-config autoconf libtool libopengl-dev libglu-dev libx11-dev libxrandr-dev libxxf86vm-dev freeglut3-dev libglm-dev libglew-dev
          version: 1.0

    - name: Install macOS dependencies with caching
      uses: tecolicom/actions-use-homebrew-tools@v1
      if: runner.os == 'macOS'
      with:
          # put your list of homebrew packages here for the dependencies you need
          tools: autoconf automake libtool libxcb freeglut glew XQuartz glm

    - name: Build (Release)
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'release'
        buildPreset: 'release'
        testPreset: 'release'

    - name: Build (Debug)
      uses: lukka/run-cmake@v10
      with:
        configurePreset: 'debug'
        configurePresetAdditionalArgs: "['-DBUILD_WITH_COVERAGE:BOOL=ON']"
        buildPreset: 'debug'
        testPreset: 'debug'

    - name: Generate coverage report (Linux and macOS)
      working-directory: ./build/debug
      run: |
        gcovr --root ../../src --print-summary --xml-pretty --xml coverage.xml .    

    - name: Publish to codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true # we weren't posting previously
        flags: ${{ runner.os }}
        name: ${{ runner.os }}-coverage
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./build/debug/coverage.xml

    - name: Upload coverage to Codacy
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ./build/debug/coverage.xml
        language: cpp
      continue-on-error: true
